services:
  frontend: 
    build: 
      context: ./grabtern-frontend
      dockerfile: Dockerfile.dev
    image: grabtern-frontend-img:1.0.0
    ports: 
      - "3000:3000"
    volumes:
      - ./grabtern-frontend:/grabtern-app  