name: 🐛 Bug
description: Report an issue to help improve the project.
labels: ["🛠 goal: fix", "🚦 status: awaiting triage"]
body:
  - type: textarea
    id: description_bug
    attributes:
      label: "Description"
      description: "Please enter clear and concise description of the bug"
      placeholder: "Short and explicit description of your incident..."
    validations:
      required: true
  - type: input
    id: reprod-url-bug
    attributes:
      label: "Reproduction URL"
      description: "Please enter your GitHub URL to provide a reproduction of the issue"
      placeholder: "ex. https://github.com/USERNAME/REPO-NAME"
  - type: textarea
    id: reprod-steps-bug
    attributes:
      label: "Reproduction steps"
      description: "Please enter an explicit description of the issue/bug"
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: bug_screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
  - type: textarea
    id: bug_logs
    attributes:
      label: "Logs"
      description: "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
      render: bash
  - type: dropdown
    id: bug_browsers
    attributes:
      label: "Browsers"
      description: "What browsers are you seeing the problem on? (Select all that apply)"
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Opera
        - Brave
  - type: dropdown
    id: bug_os
    attributes:
      label: "OS"
      description: "What is the impacted environment (operating system)? (Select all that apply)"
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
        - iOS
        - Android
  - type: textarea
    id: bug_additional_context
    attributes:
      label: "Additional Context"
      description: "Write additional information about the bug in this section."
    validations:
  - type: checkboxes
    id: bug_sections_completed
    attributes:
      label: "Sections Completed"
      description: "Check the box of the sections you have completed."
      options:
        - label: Description
        - label: Reproduction URL
        - label: Reproduction steps
        - label: Screenshots
        - label: Logs
        - label: Browsers
        - label: OS
        - label: Additional Context
  - type: checkboxes
    id: checklist_terms_bug
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/anmode/grabtern-frontend/blob/develop/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)"
          required: true
        - label: "I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)"
          required: true
        - label: "I would like to be assigned this task."
          required: false
        - label: "I am a GSSoC'23 contributor"
          required: false
