name: "📄 Documentation issue"
description: "Found an issue in the documentation? Use this template!"
title: "[DOCS] <description>"
labels: ["📄 aspect: text", "🚦 status: awaiting triage"]
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to suggest a documentation issue! Your input is greatly appreciated."
  - type: textarea
    id: description_docs
    attributes:
      label: "Description"
      placeholder: "Write a concise description of the issue with the documentation."
      description: "Provide a brief description of the changes you would like to make in the documentation."
    validations:
      required: true
  - type: textarea
    id: docs_screenshots
    attributes:
      label: Screenshots
      description: "Please add screenshots if applicable"
  - type: textarea
    id: additional_context_docs
    attributes:
      label: "Additional Context"
      description: "If you have any additional context or information that can support your point, please include it here."
      placeholder: "You can include any relevant information that justifies your statement."
  - type: checkboxes
    id: checklist_terms_docs
    attributes:
      label: Checklist
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/anmode/grabtern-frontend/blob/develop/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have checked the existing [issues](https://github.com/anmode/grabtern-frontend/issues)"
          required: true
        - label: "I have read the [Contributing Guidelines](https://github.com/anmode/grabtern-frontend/blob/develop/CONTRIBUTING.md)"
          required: true
        - label: "I would like to be assigned this task."
          required: false
        - label: "I am a GSSoC'23 contributor"
          required: false
