name: Greetings

on:
   issues:
    types: [opened]
   pull_request_target:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Greet Contributor
        id: greet
        run: |
          echo "::set-output name=greeting::$(node -e '
          // Mapping the Greetings
          const greetings = {
            collaborator: "Hello, collaborator! Thank you for your contribution. We really appreciate your help! Our team will review it and get back to you ! ",
            collaborator1: "Hello, collaborator! Thank you for your first contribution. We really appreciate your help! Our team will review it and get back to you ! ",
            owner: "Welcome, owner! We're glad to have you on board. Your expertise is valuable to us!",
            firstTimeContributor: "Hello, first-time contributor! Thank you for opening your first issue. We're excited to collaborate with you!",
            returningContributor: "Welcome back, returning contributor! Your continued contributions are greatly appreciated! We highly value your partcipation !",  
            mentor1: "Hi there, mentor! We see that it's your first time here . Thank you for offering your guidance and support. Your expertise helps us build a strong community!",
            mentor: "Hi there, mentor! Thank you for offering your guidance and support. Your expertise helps us build a strong community!",
          };
          // Get event and actor information
          const event = process.env.GITHUB_EVENT_NAME;
          const actor = process.env.GITHUB_ACTOR;
          // Determining the appropriate greeting based on the event and actor
          let greeting;
          if {
            const issueCount = Number(process.env.GITHUB_ISSUE_COUNT || 0);
          if (issueCount === 0) {
            if (actor === "collaborator") {
            greeting = greetings.collaborator1;
          } 
            else if (actor === "mentor") {
            greeting = greetings.mentor1;
          } else {
              greeting = greetings.firstTimeContributor;
            }
             }
             else {
              greeting = greetings.returningContributor;
            } 
             }
          else{
          if (actor === "collaborator") {
            greeting = greetings.collaborator;
          } else if (actor === "owner") {
            greeting = greetings.owner;
          } else if (actor === "mentor") {
            greeting = greetings.mentor;
          }
          }
          // Output the greeting
          console.log(`\n\n====================\n${greeting}\n====================\n\n`);
          ')"
      - name: Display Greeting
        run: echo "${{ steps.greet.outputs.greeting }}"