name: Prettier Code Formatting

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  prettier-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run prettier
        run: npx prettier --check .
